### ISSUE TITLE
Design review

### ISSUE THREAD

**Issue by tkilla77** [PiranhaV/Talit_Projekt_2024#1]
- [x]  [PRD](../blob/main/project_draft.md) approved.
- [x] [Design](../blob/main/design_doc_dario.md) looking good in general
  - [x] Basic mechanical design stated
    - [x] A sketch / drawing would be nice to imagine motor placement
    - [x] Weight estimation of {base board, solar panel} would help to estimate required motor strength.
  - [x] Planning: OK to plan for next few weeks
    - [x] Please add: next check-in time (=milestone) and what you plan to show to the supervisors then.

**Comment by tkilla77** [comment]
@anschae

**Comment by PiranhaV** [comment]
Last commit added an obj file to describe the (very) rough placement of the motors. Weight estimate is in the design doc.

**Comment by tkilla77** [comment]
Nice - is there a way to add a rendering of the sketch to the design doc (so I don't need to fire up blender)?

**Comment by tkilla77** [comment]
Re. planning - I understand it's hard to make any robust estimation at this point. The plan does have fine-granular goals for the next few weeks, so I'll approve the design and planning.

Please come back by mid March with the mounting prototype and possibly more according to plan.

As mentioned, a very rough draft / sketch of the planned product would be nice.
