### ISSUE TITLE
Parts order

### ISSUE THREAD

**Issue by PiranhaV** [PiranhaV/Talit_Projekt_2024#2]
We have compiled a list of parts together with their respective links and amounts. You can find the list under the link below.
[parts_order.xlsx](https://github.com/PiranhaV/Talit_Projekt_2024/blob/main/design_project_docs/parts_order.xlsx)

**Comment by tkilla77** [comment]
A few questions:
  * why 4 motors - do you plan to move the thermal camera separately from the panel?
    * I see you have two panels - reason?
  * why 4 motors but only 2 controllers (can a controller control 2 motors? Descriptions says it can only handle 2 DC motors, but only one stepping motor at a time...)
  * is the battery-powering necessary for V1, or can this be delayed?
    * the entire question of self-powering (charge battery from solar array, then use battery to re-start when the sun raises) has not been addressed in the PRD (but would indeed make sense).

**Comment by PiranhaV** [comment]
* The camera will be mounted on a seperate mount, therefore we require 4 motors. This would make it theoretically possible to connect and infinite amount of panels to the control unti.
* Two panels in case one of them breaks
* We didn't see that, will correct
* Can be delayed, idea was to order once instead of multiple, partial orders

**Comment by tkilla77** [comment]
Parts ordered, except for lead batteries as discussed.
